N = 3926
ID = $(Cluster).$(Process) 

Universe       = vanilla
Initialdir     = /gpfs/mnt/gpfs02/phenix/mpcex/cperez/Run16dAu_MB/
Executable     = /bin/csh
Arguments      = dojob.csh $(Process)

Notification   = Error
Log            = log/_$(Cluster).log
Output         = log/_$(ID).out
Error          = log/_$(ID).err
Requirements   = (CPU_Speed >= 1)

Priority       = +20
GetEnv         = True
+Job_Type      = "highmem"
request_memory = 1.8GB


Queue $(N)
